@port = 3002
@host = localhost:{{port}}
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUR0wgU29sdXRpb25zIiwiZXhwIjoiMjAyNC0wNS0xMlQxNzo1Nzo0My40MTgyNzQrMDc6MDAiLCJ1c2VyX2lkIjo5fQ.D-WNe7osPWv9IO8T-Op0pPeqKilM4WHPia5KVlK0C5U
@client = clients
@note = notes
@client-uuid = af9bbc4e-a898-4baa-aa6c-5eb63c35ad95

###########
# CLIENT NOTE ACTIVITIES #
###########

###
# Read List
GET http://{{host}}/api/v1/clients/{{client-uuid}}/note_activities HTTP/1.1
{{token}}
###
