@port = 3002
@host = localhost:{{port}}
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUR0wgU29sdXRpb25zIiwiZXhwIjoiMjAyNC0wNS0xMlQxNjoyMjozOC45NDI3NjMrMDc6MDAiLCJ1c2VyX2lkIjo5fQ.mAAp_Iu2vYpBKEZ37usr4-CK3R0KuTpJahHExk0zpY4
@user = users

###########
# AUTH #
###########
# Register
POST http://{{host}}/api/v1/register HTTP/1.1
Content-Type: application/json

{"username":"abcdef","password":"123456","displayname":"Le Van Vuong","email":"abcdef123456@gmail.com","organization_name":"ABC Company"}

###########
# AUTH #
###########
# Me
GET http://{{host}}/api/v1/me HTTP/1.1
{{token}}
###

###########
# AUTH #
###########
# Create
POST https://sky-crm.click/api/v1/auth HTTP/1.1
Content-Type: application/json

{"username":"0000","password":"123456"}

###