curl -X POST http://localhost:3002/api/v1/clients \
    -H "Content-Type: multipart/form-data" \
    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUR0wgU29sdXRpb25zIiwiZXhwIjoiMjAyNC0wNS0xMlQxNzo1Nzo0My40MTgyNzQrMDc6MDAiLCJ1c2VyX2lkIjo5fQ.D-WNe7osPWv9IO8T-Op0pPeqKilM4WHPia5KVlK0C5U" \
    -F "image=@/Users/huynhtrongtien/Downloads/logo_1.jpeg" \
    -F "fullname=Fullname12" \
    -F "shortname=Shortname11" \
    -F "code=Code11" \
    -F "phone=Phone11" \
    -F "fax=Fax11" \
    -F "website=Website11" \
    -F "email=Email11" \
    -F "company_size=CompanySize11" \
    -F "address=Address11" \
    -F "new_contact={\"fullname\":\"NguyenVanA\",\"email\":\"nguyenvana@gmail.com\"};type=application/json"